[package]
name = "story_gen"
version = "0.1.0"
edition = "2018"
authors = ["Nathan Larkin <nlarkin.us@gmail.com>"]
repository = "https://github.com/nalarkin/story-generator"
license = "MIT"
readme = "README.md"

[dependencies]
rand = "0.8.4"